[package]
name = "tuisko-remote"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
flate2.workspace = true
russh.workspace = true
russh-sftp.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tuisko-targets.workspace = true
ureq.workspace = true

[lints]
workspace = true
