[package]
name = "tuisko-serve"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tuisko-engine.workspace = true
tuisko-frontend.workspace = true
tuisko-model.workspace = true

[lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[lints.rustdoc]
broken_intra_doc_links = "deny"
